# Generated by Django 4.0.2 on 2022-02-05 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sz', '0002_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='match',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
